# Generated by Django 6.0.6 on 2026-06-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='blog/media/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'post media',
                'ordering': ['-created_at'],
            },
        ),
    ]
