# Generated by Django 6.0.6 on 2026-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_author_email_alter_comment_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvotes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
