# Generated by Django 6.0.6 on 2026-07-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reply_to_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                verbose_name="in reply to URL",
            ),
        ),
    ]
