# Generated by Django 6.0.6 on 2026-07-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_post_reply_to_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reply_to_title",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="in reply to title",
            ),
        ),
    ]
