# Generated by Django 6.0.6 on 2026-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_post_reply_to_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notes",
                        to="blog.tag",
                    ),
                ),
            ],
            options={"ordering": ["-published_at"]},
        ),
    ]
