# Generated by Django 6.0.6 on 2026-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('client_id', models.URLField(blank=True, max_length=500)),
                ('scope', models.CharField(blank=True, max_length=300)),
                ('me', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('client_id', models.URLField(max_length=500)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('code_challenge', models.CharField(blank=True, max_length=256)),
                ('code_challenge_method', models.CharField(default='S256', max_length=16)),
                ('scope', models.CharField(blank=True, max_length=300)),
                ('me', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
