# Generated by Django 6.0.6 on 2026-08-12 18:42

import birdex.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('endemic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('confidence', models.CharField(choices=[('tentative', 'Tentative'), ('probable', 'Probable'), ('high', 'High'), ('certain', 'Certain')], default='tentative', max_length=20)),
                ('verification', models.CharField(choices=[('unverified', 'Unverified'), ('community', 'Community confirmed'), ('expert', 'Expert confirmed')], default='unverified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='birdex.bird')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SightingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=birdex.models.birdex_storage, upload_to='birdex/photos/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='birdex.sighting')),
            ],
        ),
    ]
