# Generated by Django 6.0.6 on 2026-08-12 18:51

import birdex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightingphoto',
            name='image',
            field=models.ImageField(storage=birdex.models.birdex_storage, upload_to=birdex.models.birdex_photo_upload_to),
        ),
    ]
