# Generated by Django 6.0.6 on 2026-08-12 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdex', '0002_alter_sightingphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
