# Generated by Django 6.0.6 on 2026-08-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdex', '0003_sighting_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='ebird_url',
            field=models.URLField(blank=True, help_text='Paste the complete eBird species-profile URL.', verbose_name='eBird species profile'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=models.TextField(blank=True, help_text='Keep this personal: what makes the bird memorable, where you encounter it, behavior you have noticed, and what makes it interesting to photograph.'),
        ),
    ]
