# Generated by Django 6.0.6 on 2026-08-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdex', '0004_bird_ebird_url_alter_bird_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', help_text='Draft sightings are only visible in the admin.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank to use the time the sighting is published.', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Draft sightings are only visible in the admin.', max_length=20),
        ),
    ]
