# Generated by Django 6.0.6 on 2026-06-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webmentions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentWebmention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(max_length=500)),
                ("target_url", models.URLField(max_length=500)),
                ("endpoint_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("no_endpoint", "No endpoint"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-last_sent_at", "-created_at"],
                "unique_together": {("source_url", "target_url")},
            },
        ),
    ]
